all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: centos
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    ec2-54-201-218-181.us-west-2.compute.amazonaws.com:
    ec2-52-10-180-68.us-west-2.compute.amazonaws.com:
    ec2-34-219-234-72.us-west-2.compute.amazonaws.com:
    ec2-34-217-35-184.us-west-2.compute.amazonaws.com:
zookeeper:
  hosts:
    ec2-54-201-218-181.us-west-2.compute.amazonaws.com:
    ec2-52-10-180-68.us-west-2.compute.amazonaws.com:
    ec2-34-219-234-72.us-west-2.compute.amazonaws.com:
broker:
  hosts:
    ec2-54-201-218-181.us-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 1
    ec2-52-10-180-68.us-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 2
    ec2-34-219-234-72.us-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    ec2-34-217-35-184.us-west-2.compute.amazonaws.com:
control-center:
  hosts:
    ec2-34-217-35-184.us-west-2.compute.amazonaws.com:
